### ISSUE TITLE
python remi build an App to connect douban.com but can't download jpg from douban.com

### ISSUE THREAD

**Issue by michael10297** [rawpython/remi#484]
I create an App by python remi to connect douban.com and download some jpg. but fail and shows
'
[https://movie.douban.com:443](https://movie.douban.com/) "GET /subject/1949521/ HTTP/1.1" 200 None
urllib3.connectionpool DEBUG    Starting new HTTPS connection (1): movie.douban.com:443
urllib3.connectionpool DEBUG    [https://movie.douban.com:443](https://movie.douban.com/) "GET /subject/1949521/comments HTTP/1.1" '
only download fail, connect web is successful.
before this, I can download jpg from douban.com by wxpython.

**Comment by michael10297** [comment]
mistake on a variable.

**Comment by dddomodossola** [comment]
Well done ;-)
