### ISSUE TITLE
How does the Remi server page keep accepting requests from 77.111.244.11?

### ISSUE THREAD

**Issue by Ambassador-pi** [rawpython/remi#485]
How does the Remi server page keep accepting requests from 77.111.244.11?
remi.server.ws   INFO     connection established: ('77.111.244.11', 45063)
remi.server.ws   INFO     handshake complete

**Comment by dddomodossola** [comment]
It depends on the parameter of the function **start()**. If you do **start('0.0.0.0')**, remi listens on all interfaces. If you set a specific ip address,  remi will listen only on that specific one.
