### ISSUE TITLE
Question about playing RTSP.

### ISSUE THREAD

**Issue by Antonio0307** [rawpython/remi#487]

**Comment by Antonio0307** [comment]
Play the camera RTSP on the Web  ，however, the video pause......pause.....pause,I don't know what the problem is........Could it be a thread problem?How to solve it?        Another question  "videoplay",Whether RTSP can be played？

**Comment by Antonio0307** [comment]
![QQ图片20220401130557](https://user-images.githubusercontent.com/91074713/161198380-ba6566e8-a853-4bab-bb5a-5449fece9920.png)

**Comment by Antonio0307** [comment]
It's a simple thing。I want to see the video from the camera on the Web。But OpencVVideo is very fluid, and VideoPlay doesn't work, oddly.  @[dddomodossola，thank you :)

**Comment by dddomodossola** [comment]
Hello @Antonio0307 ,

I never played with RTSP. However, searching on the web I found this https://www.videoconverterfactory.com/tips/rtsp-html5.html .
At the top of the webpage it is written: "One can't directly play RTSP (Real Time Streaming Protocol) streams on HTML5 webpage since RTSP is not supported by the HTML5 <video> tag. But RTSP HTML5 playback is achievable if you transcode RTSP to HTTP, and you can also implement RTSP live streaming by doing so. Keep reading and I'll show you how."

So you cannot directly play RTSP with video widget.

If opencv video widget is slow, you can increase the "framerate" attribute. 

If this is not enough, you can consider to compress the frames in jpeg or png. This have to be done inside the OpencvVideo widget code. Look at the method "def get_image_data(...):" in the line where it does cv2.imencode(".png", frame), here you can consider to compress or resize the image.

```python
class OpencvVideo(OpencvImage):
    """ OpencvVideo widget.
        Opens a video source and dispatches the image frame by generating on_new_image event.
        The event on_new_image can be connected to other Opencv widgets for further processing
    """
    icon = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFoAAAAuCAYAAACoGw7VAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAKyAAACsgBvRoNowAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAXdSURBVHic7ZptTFNnFMf/z21rX1baQi0MBGojoesUJeJLNBhw6oddk5YuY2LMMjMSzLIYDCZLtsTEGbPpwvi0LQsSpgkpYRFDhpGYRVCnxCWObTi/YJ2ogKuDXspLwd7bPvsAmikKvaXlUuD3pcl9Oed//3l67rknD8ESMcXpdBqDweApIrWQ+U5xcbGM5/kMnucZsfcSQjYyDFNJKdUtGf0SWJY1MwzzPiHkHUqpiRDCUEqp2DiEEA2ARAB98ujLjF92795tk8lkVZTSXADJABhCJtbi099IWTIaQFlZmeLRo0fVAN6mlKbEIseiLx1Op9MoCEILgDUA1DFK0ye6wC8kWJbNFQThJoA8xM5kAIu4dNjt9g8opScBhFsqPJRSr5gchJDXAJgAkEVn9NGjR5mOjo5vQ6HQe4SQpDBv8wDYc/78+SticpWVlSn6+vqOE0IORaVGFxUVrQqFQvnRiBVj1AAOUUpXUUqfMAwj/P8kpZTg+fdWcPL49yMjI59fvnx5PJKkDofjzagYbbfbP5n8Gy5UgsFgcNWFCxfuRxqA4Xn+BKXUEk1VS0yF4Xm+/N69ex39/f03BUFwUEplUotaiMj9fr+/vLw8KT09PY9l2R+2bdsWGB4e/lGr1VYSQh7MJnhBTw/e6ukBAFxLS8PPmZkAgDvFdzCwZgAAkHUuC8v/XD7Lx5j/POuje3p6UF1dnVhaWppSU1PzUW9v7x+Dg4O/CYJgn3xJiCbN74eV42DlOKwYHX12fMgyBM7KgbNyGE+K6P0Sd0xp7wKBAFpbW+Wtra2JWVlZiXa7/cy6devGfD7fKZ1O9w0h5N9wg9dnZ6M+O3vK8byv8mYpO/6Yto92u92oqqoyaDQaQ0FBwadFRUUfcxz3u8FgOAngEiFE9ERrsRLWJ7jf70dLS4viwIEDxmPHju28evVqvc/nuz82NnaEUhpu07+oET3rcLvdqKysXH7w4MGMxsbGz7xeb9e+fftyYyFuIRHxJ/jg4CAaGhpUHo9HtX79elM0RS1EFvX0bi5ZMnqOWDJ6jpgXY1KLxYKSkhKkpaVBrY7u/D0QCODx48doa2vDlSuippxRRXKjLRYLKioq4HK50N3dHZMcKSkp2LlzJ6xWK6qrq2OSYyYkLx379+9HXV1dzEwGAI/HA5fLBavViuTk5JjlmQ5JjU5ISIBOp8ODB7OaXYUFpRSdnZ3IycmJea6XIanRK1eunBOTn+L1emEySdPyS146QqHQjNe0l7Sja2vXrHPxPI9ly5bNOk4kSG50OHCvc7hech1nj5wFl8pJLSci4sJoAOCVPLzpXjQfbkbbh20IqAJSSxJFxO2d2WyGw+Hwbdq0abyxsfFhNEVNx3jCONwb3eh9oxd5zXmwXbMBcTCsFWW0QqHA5s2bqcPh8JpMpod6vf5LmUx2rqmpqSJWAl8GZSj8ej9uvHsDt7ffxo6aHUjsS5xLCaIJy+jU1FSwLDtSWFjIA2jS6/XHCSF/Pz1vt9tjJnA6eBUP74qJcpLxVwby6/OhGFdIomUmXmk0wzDIycmhe/fuHUhPT/dptdpKhmHOEELG5lJgOIxrJ8uJbbKc/GKTWtIUphidlJSEXbt2jbAsO8YwzCW9Xv8FIeSWFOLEQGUT5aR9Tzs0Pg3MnWapJT2HHJjYZL127Vo4nU7OYrEMajSar5VK5WlCyOhMAeYLylElDP8YsL12O3T9OqnlTEGu0+k0tbW1AzKZrNVgMJwghHRILUoM8idyaIY02NqwFZm3MqWW80rkCoXisNForCOEDEktRgwkRKAeVmN122rkXswFCc3vPfVyQsh3UosQi3pYjdSuVOS78qEaUUktJywkn0eLQTmqhK5fh8LThfO+b36RuDCaCTLQerXId+XP6zo8HXFh9IbmDTA+NIIJxs1oZgpxYbSpO/63jcTvEokzorKiQ6HQRQDCjBe+gNlsztqyZUupzWbjo6FjJlQqlezu3bu/Ukp/EnMfwzBEEIT+2eT+D23+73+IM13aAAAAAElFTkSuQmCC"

    capture = None              #the cv2 VideoCapture
    thread_stop_flag = False    #a flag to stop the acquisition thread
    thread = None #             the update thread

    @property
    @gui.editor_attribute_decorator('WidgetSpecific','The refresh interval in Hz', int, {'default':0, 'min':0, 'max':65535, 'step':1})
    def framerate(self): return self.__framerate
    @framerate.setter
    def framerate(self, v): self.__framerate = v;

    @property
    @gui.editor_attribute_decorator('WidgetSpecific','The video source index', int, {'default':0, 'min':0, 'max':65535, 'step':1})
    def video_source(self): return self.__video_source
    @video_source.setter
    def video_source(self, v): self.__video_source = v; self.capture = cv2.VideoCapture(self.__video_source)

    def __init__(self, *args, **kwargs):
        self.framerate = 10
        self.video_source = 0
        super(OpencvVideo, self).__init__("", *args, **kwargs)
        self.thread = Thread(target=self.update)
        self.thread.daemon = True
        self.thread.start()

    def set_image_data(self, image_data_as_numpy_array):
        #oveloaded to avoid update
        self.img = image_data_as_numpy_array

    def search_app_instance(self, node):
        if issubclass(node.__class__, remi.server.App):
            return node
        if not hasattr(node, "get_parent"):
            return None
        return self.search_app_instance(node.get_parent()) 

    def __del__(self):
        self.thread_stop_flag = True
        super(OpencvVideo, self).__del__()

    def update(self, *args):
        while not self.thread_stop_flag:
            time.sleep(1.0/self.framerate)
            if self.app_instance==None:
                self.app_instance = self.search_app_instance(self)
                if self.app_instance==None:
                    continue

            with self.app_instance.update_lock:
                self.app_instance.execute_javascript("""
                    var url = '/%(id)s/get_image_data?index=%(frame_index)s';
                    var xhr = new XMLHttpRequest();
                    xhr.open('GET', url, true);
                    xhr.responseType = 'blob'
                    xhr.onload = function(e){
                        var urlCreator = window.URL || window.webkitURL;
                        urlCreator.revokeObjectURL(document.getElementById('%(id)s').src);
                        var imageUrl = urlCreator.createObjectURL(this.response);
                        document.getElementById('%(id)s').src = imageUrl;
                    }
                    xhr.send();
                    """ % {'id': self.identifier, 'frame_index':str(time.time())})
                

    def get_image_data(self, index=0):
        gui.Image.set_image(self, '/%(id)s/get_image_data?index=%(frame_index)s'% {'id': self.identifier, 'frame_index':str(time.time())})
        self._set_updated()
        try:
            ret, frame = self.capture.read()
            if ret:
                self.set_image_data(frame)
                self.on_new_image()
                ret, png = cv2.imencode('.png', frame)
                if ret:
                    headers = {'Content-type': 'image/png', 'Cache-Control':'no-cache'}
                    # tostring is an alias to tobytes, which wasn't added till numpy 1.9
                    return [png.tostring(), headers]
        except Exception:
            print(traceback.format_exc())
        return None, None
```

Kind Regards,
Davide

**Comment by Antonio0307** [comment]
> Hello @Antonio0307 ,
> 
> I never played with RTSP. However, searching on the web I found this https://www.videoconverterfactory.com/tips/rtsp-html5.html . At the top of the webpage it is written: "One can't directly play RTSP (Real Time Streaming Protocol) streams on HTML5 webpage since RTSP is not supported by the HTML5
> 
> So you cannot directly play RTSP with video widget.
> 
> If opencv video widget is slow, you can increase the "framerate" attribute.
> 
> If this is not enough, you can consider to compress the frames in jpeg or png. This have to be done inside the OpencvVideo widget code. Look at the method "def get_image_data(...):" in the line where it does cv2.imencode(".png", frame), here you can consider to compress or resize the image.
> 
> ```python
> class OpencvVideo(OpencvImage):
>     """ OpencvVideo widget.
>         Opens a video source and dispatches the image frame by generating on_new_image event.
>         The event on_new_image can be connected to other Opencv widgets for further processing
>     """
>     icon = "data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFoAAAAuCAYAAACoGw7VAAAABHNCSVQICAgIfAhkiAAAAAlwSFlzAAAKyAAACsgBvRoNowAAABl0RVh0U29mdHdhcmUAd3d3Lmlua3NjYXBlLm9yZ5vuPBoAAAXdSURBVHic7ZptTFNnFMf/z21rX1baQi0MBGojoesUJeJLNBhw6oddk5YuY2LMMjMSzLIYDCZLtsTEGbPpwvi0LQsSpgkpYRFDhpGYRVCnxCWObTi/YJ2ogKuDXspLwd7bPvsAmikKvaXlUuD3pcl9Oed//3l67rknD8ESMcXpdBqDweApIrWQ+U5xcbGM5/kMnucZsfcSQjYyDFNJKdUtGf0SWJY1MwzzPiHkHUqpiRDCUEqp2DiEEA2ARAB98ujLjF92795tk8lkVZTSXADJABhCJtbi099IWTIaQFlZmeLRo0fVAN6mlKbEIseiLx1Op9MoCEILgDUA1DFK0ye6wC8kWJbNFQThJoA8xM5kAIu4dNjt9g8opScBhFsqPJRSr5gchJDXAJgAkEVn9NGjR5mOjo5vQ6HQe4SQpDBv8wDYc/78+SticpWVlSn6+vqOE0IORaVGFxUVrQqFQvnRiBVj1AAOUUpXUUqfMAwj/P8kpZTg+fdWcPL49yMjI59fvnx5PJKkDofjzagYbbfbP5n8Gy5UgsFgcNWFCxfuRxqA4Xn+BKXUEk1VS0yF4Xm+/N69ex39/f03BUFwUEplUotaiMj9fr+/vLw8KT09PY9l2R+2bdsWGB4e/lGr1VYSQh7MJnhBTw/e6ukBAFxLS8PPmZkAgDvFdzCwZgAAkHUuC8v/XD7Lx5j/POuje3p6UF1dnVhaWppSU1PzUW9v7x+Dg4O/CYJgn3xJiCbN74eV42DlOKwYHX12fMgyBM7KgbNyGE+K6P0Sd0xp7wKBAFpbW+Wtra2JWVlZiXa7/cy6devGfD7fKZ1O9w0h5N9wg9dnZ6M+O3vK8byv8mYpO/6Yto92u92oqqoyaDQaQ0FBwadFRUUfcxz3u8FgOAngEiFE9ERrsRLWJ7jf70dLS4viwIEDxmPHju28evVqvc/nuz82NnaEUhpu07+oET3rcLvdqKysXH7w4MGMxsbGz7xeb9e+fftyYyFuIRHxJ/jg4CAaGhpUHo9HtX79elM0RS1EFvX0bi5ZMnqOWDJ6jpgXY1KLxYKSkhKkpaVBrY7u/D0QCODx48doa2vDlSuippxRRXKjLRYLKioq4HK50N3dHZMcKSkp2LlzJ6xWK6qrq2OSYyYkLx379+9HXV1dzEwGAI/HA5fLBavViuTk5JjlmQ5JjU5ISIBOp8ODB7OaXYUFpRSdnZ3IycmJea6XIanRK1eunBOTn+L1emEySdPyS146QqHQjNe0l7Sja2vXrHPxPI9ly5bNOk4kSG50OHCvc7hech1nj5wFl8pJLSci4sJoAOCVPLzpXjQfbkbbh20IqAJSSxJFxO2d2WyGw+Hwbdq0abyxsfFhNEVNx3jCONwb3eh9oxd5zXmwXbMBcTCsFWW0QqHA5s2bqcPh8JpMpod6vf5LmUx2rqmpqSJWAl8GZSj8ej9uvHsDt7ffxo6aHUjsS5xLCaIJy+jU1FSwLDtSWFjIA2jS6/XHCSF/Pz1vt9tjJnA6eBUP74qJcpLxVwby6/OhGFdIomUmXmk0wzDIycmhe/fuHUhPT/dptdpKhmHOEELG5lJgOIxrJ8uJbbKc/GKTWtIUphidlJSEXbt2jbAsO8YwzCW9Xv8FIeSWFOLEQGUT5aR9Tzs0Pg3MnWapJT2HHJjYZL127Vo4nU7OYrEMajSar5VK5WlCyOhMAeYLylElDP8YsL12O3T9OqnlTEGu0+k0tbW1AzKZrNVgMJwghHRILUoM8idyaIY02NqwFZm3MqWW80rkCoXisNForCOEDEktRgwkRKAeVmN122rkXswFCc3vPfVyQsh3UosQi3pYjdSuVOS78qEaUUktJywkn0eLQTmqhK5fh8LThfO+b36RuDCaCTLQerXId+XP6zo8HXFh9IbmDTA+NIIJxs1oZgpxYbSpO/63jcTvEokzorKiQ6HQRQDCjBe+gNlsztqyZUupzWbjo6FjJlQqlezu3bu/Ukp/EnMfwzBEEIT+2eT+D23+73+IM13aAAAAAElFTkSuQmCC"
> 
>     capture = None              #the cv2 VideoCapture
>     thread_stop_flag = False    #a flag to stop the acquisition thread
>     thread = None #             the update thread
> 
>     @property
>     @gui.editor_attribute_decorator('WidgetSpecific','The refresh interval in Hz', int, {'default':0, 'min':0, 'max':65535, 'step':1})
>     def framerate(self): return self.__framerate
>     @framerate.setter
>     def framerate(self, v): self.__framerate = v;
> 
>     @property
>     @gui.editor_attribute_decorator('WidgetSpecific','The video source index', int, {'default':0, 'min':0, 'max':65535, 'step':1})
>     def video_source(self): return self.__video_source
>     @video_source.setter
>     def video_source(self, v): self.__video_source = v; self.capture = cv2.VideoCapture(self.__video_source)
> 
>     def __init__(self, *args, **kwargs):
>         self.framerate = 10
>         self.video_source = 0
>         super(OpencvVideo, self).__init__("", *args, **kwargs)
>         self.thread = Thread(target=self.update)
>         self.thread.daemon = True
>         self.thread.start()
> 
>     def set_image_data(self, image_data_as_numpy_array):
>         #oveloaded to avoid update
>         self.img = image_data_as_numpy_array
> 
>     def search_app_instance(self, node):
>         if issubclass(node.__class__, remi.server.App):
>             return node
>         if not hasattr(node, "get_parent"):
>             return None
>         return self.search_app_instance(node.get_parent()) 
> 
>     def __del__(self):
>         self.thread_stop_flag = True
>         super(OpencvVideo, self).__del__()
> 
>     def update(self, *args):
>         while not self.thread_stop_flag:
>             time.sleep(1.0/self.framerate)
>             if self.app_instance==None:
>                 self.app_instance = self.search_app_instance(self)
>                 if self.app_instance==None:
>                     continue
> 
>             with self.app_instance.update_lock:
>                 self.app_instance.execute_javascript("""
>                     var url = '/%(id)s/get_image_data?index=%(frame_index)s';
>                     var xhr = new XMLHttpRequest();
>                     xhr.open('GET', url, true);
>                     xhr.responseType = 'blob'
>                     xhr.onload = function(e){
>                         var urlCreator = window.URL || window.webkitURL;
>                         urlCreator.revokeObjectURL(document.getElementById('%(id)s').src);
>                         var imageUrl = urlCreator.createObjectURL(this.response);
>                         document.getElementById('%(id)s').src = imageUrl;
>                     }
>                     xhr.send();
>                     """ % {'id': self.identifier, 'frame_index':str(time.time())})
>                 
> 
>     def get_image_data(self, index=0):
>         gui.Image.set_image(self, '/%(id)s/get_image_data?index=%(frame_index)s'% {'id': self.identifier, 'frame_index':str(time.time())})
>         self._set_updated()
>         try:
>             ret, frame = self.capture.read()
>             if ret:
>                 self.set_image_data(frame)
>                 self.on_new_image()
>                 ret, png = cv2.imencode('.png', frame)
>                 if ret:
>                     headers = {'Content-type': 'image/png', 'Cache-Control':'no-cache'}
>                     # tostring is an alias to tobytes, which wasn't added till numpy 1.9
>                     return [png.tostring(), headers]
>         except Exception:
>             print(traceback.format_exc())
>         return None, None
> ```
> 
> Kind Regards, Davide

thank you very much! I solved it yesterday.
It's simple. Set up the camera。
Of course, I'll study your plan carefully ： ）

**Comment by Antonio0307** [comment]
Your plan is obviously better ！
![src=http%3A%2F%2Fyanxuan nosdn 127 net%2F2f402915e3ad6156455fe7a818819dc9 jpg refer=http%3A%2F%2Fyanxuan nosdn 127 webp](https://user-images.githubusercontent.com/91074713/162427633-4e9ba1c8-f923-4a74-bf91-84d1f86cff58.jpg)

**Comment by dddomodossola** [comment]
😉👍
