### ISSUE TITLE
Hello, I have a program made with remi, and there is a problem with the page layout disorder between different devices. I look forward to your reply!

### ISSUE THREAD

**Issue by charles114** [rawpython/remi#498]
Hello, I have a program made with remi. On the computer I developed, the layout of all web pages is normal.  But when the program runs on my other computer, the page layout is wrong!  What is the problem?  (The screen resolutions of the two computers are inconsistent) Looking forward to your reply!

**Comment by Antonio0307** [comment]
I've been in this situation before.All parts must be placed in containers.

**Comment by Antonio0307** [comment]
> Hello, I have a program made with remi. On the computer I developed, the layout of all web pages is normal. But when the program runs on my other computer, the page layout is wrong! What is the problem? (The screen resolutions of the two computers are inconsistent) Looking forward to your reply!

这个情况我遇到过，我后来搞定了。

**Comment by charles114** [comment]
> 我以前也遇到过这种情况。所有零件都必须放在容器中。

Hello, I put all the controls in a container0.  So how should I set

**Comment by charles114** [comment]
> > 您好，我有一个用 remi 制作的程序。在我开发的电脑上，所有网页的布局都是正常的。但是当程序在我的另一台电脑上运行时，页面布局是错误的！问题是什么？（两台电脑屏幕分辨率不一致）期待您的回复！
> 
> 这种情况我遇到了，我后来搞定了。

How did you get it done?

**Comment by charles114** [comment]
> I've been in this situation before.All parts must be placed in containers.

Hello, I put all the controls in a container0.  So how should I set

**Comment by Antonio0307** [comment]
你还能说中文啊？



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 18, 2022 22:04 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rawpython/remi] Hello, I have a program made with remi, andthere is a problem with the page layout disorder between different devices. Ilook forward to your reply! (Issue #498)




   
您好，我有一个用 remi 制作的程序。在我开发的电脑上，所有网页的布局都是正常的。但是当程序在我的另一台电脑上运行时，页面布局是错误的！问题是什么？（两台电脑屏幕分辨率不一致）期待您的回复！
  
这种情况我遇到了，我后来搞定了。
  
How did you get it done?

**Comment by charles114** [comment]
> 你能说中文啊？
> […](#)
> ---原创---来自：***@***.***> 日期：2022 年 9 月 18 日星期日 22:04 PM 收件人：***@***.***>; 抄送：***@***.******@***.***>; 主题： Re: [rawpython/remi] 你好，我有一个用remi做的程序，不同设备之间出现页面布局错乱的问题。我期待你的回复！（问题#498）你好，我有一个用remi制作的程序。在我开发的电脑上，所有网页的布局都是正常的。但是程序在我的另一台电脑上运行时，页面布局是两台问题的屏幕回复了，是什么情况？— 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您发表了评论。消息 ID：***@***.***>

可以呀

**Comment by charles114** [comment]
> > 您好，我有一个用 remi 制作的程序。在我开发的电脑上，所有网页的布局都是正常的。但是当程序在我的另一台电脑上运行时，页面布局是错误的！问题是什么？（两台电脑屏幕分辨率不一致）期待您的回复！
> 
> 这种情况我遇到了，我后来搞定了。

你是怎么搞定的

**Comment by Antonio0307** [comment]
你必须把部件放到hbox和hbox当中，哪怕是一个部件。另外尺寸要统一，不能这个用px那个用%。否则很容易出你碰到的问题。



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 18, 2022 22:30 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rawpython/remi] Hello, I have a program made with remi, andthere is a problem with the page layout disorder between different devices. Ilook forward to your reply! (Issue #498)




  
你能说中文啊？
 …
 ***@***.***&gt; 日期：2022 年 9 月 18 日星期日 22:04 PM ***@***.***&gt;; ***@***.***@.&gt;; 主题： Re: [rawpython/remi] 你好，我有一个用remi做的程序，不同设备之间出现页面布局错乱的问题。我期待你的回复！（问题#498）你好，我有一个用remi制作的程序。在我开发的电脑上，所有网页的布局都是正常的。但是程序在我的另一台电脑上运行时，页面布局是两台问题的屏幕回复了，是什么情况？— 直接回复此电子邮件，在 GitHub 上查看，或取消订阅。您收到此消息是因为您发表了评论。消息 ***@***.******&gt;
  
可以呀

**Comment by charles114** [comment]
> 你必须把那个盒子和那个盒子放在一起，这是一个组件。很不同，要统一不能用 px 那个用%。否则容易出你盒子的问题。
> […](#)
> ---原创---来自：***@***.***> 日期：2022 年 9 月 18 日星期日 22:30 PM 收件人：***@***.***>; 抄送：***@***.******@***.***>; 主题： Re: [rawpython/remi] 你好，我有一个用remi做的程序，不同设备之间出现页面布局错乱的问题。我期待你的回复！(Issue #498 ) 你能说中文啊？ ... ***@***.***> 日期：2022 年 9 月 18 日下午 22:04 ***@***.***>; ***@***.***@.>; 主题： Re: [rawpython/remi] 你好，我有一个用remi做的程序，不同设备之间出现页面布局错乱的问题。我期待你的回复！（问题#498）你好，我有一个用处remi制作的程序。在我开发的电脑上，所有网页的布局都是正常运行的。程序在我的台电脑上回复的时候，页面布局是两台的屏幕了，但是是什么情况？—直接回复此邮件，在 GitHub 上查看，或取消订阅。收到此消息是因为您发表了评论。消息***@***.******> 可以呀——直接回复这封邮件，在 GitHub 上查看，或者退订。您收到此消息是因为您发表了评论。消息 ID：***@***。

有微信不 ，一起交流下

**Comment by Antonio0307** [comment]
> > 你必须把那个盒子和那个盒子放在一起，这是一个组件。很不同，要统一不能用 px 那个用%。否则容易出你盒子的问题。
> > […](#)
> > ---原创---来自：_**@**_._**> 日期：2022 年 9 月 18 日星期日 22:30 PM 收件人：**_@_**.**_>; 抄送：_**@**_._**_**@**_.**_>; 主题： Re: [rawpython/remi] 你好，我有一个用remi做的程序，不同设备之间出现页面布局错乱的问题。我期待你的回复！(Issue #498 ) 你能说中文啊？ ... _**@**_._**> 日期：2022 年 9 月 18 日下午 22:04 _**@**_.**_>; _**@**_._**@.>; 主题： Re: [rawpython/remi] 你好，我有一个用remi做的程序，不同设备之间出现页面布局错乱的问题。我期待你的回复！（问题#498）你好，我有一个用处remi制作的程序。在我开发的电脑上，所有网页的布局都是正常运行的。程序在我的台电脑上回复的时候，页面布局是两台的屏幕了，但是是什么情况？—直接回复此邮件，在 GitHub 上查看，或取消订阅。收到此消息是因为您发表了评论。消息**_@_**.**__**> 可以呀——直接回复这封邮件，在 GitHub 上查看，或者退订。您收到此消息是因为您发表了评论。消息 ID：**_@***。
> 
> 有微信不 ，一起交流下

你找QQ群python remi .加下。

**Comment by Antonio0307** [comment]
你qq找python remi群



---Original---
From: ***@***.***&gt;
Date: Sun, Sep 18, 2022 22:35 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rawpython/remi] Hello, I have a program made with remi, andthere is a problem with the page layout disorder between different devices. Ilook forward to your reply! (Issue #498)




  
你必须把那个盒子和那个盒子放在一起，这是一个组件。很不同，要统一不能用 px 那个用%。否则容易出你盒子的问题。
 …
 ***@***.***&gt; 日期：2022 年 9 月 18 日星期日 22:30 PM ***@***.***&gt;; ***@***.***@.&gt;; 主题： Re: [rawpython/remi] 你好，我有一个用remi做的程序，不同设备之间出现页面布局错乱的问题。我期待你的回复！(Issue #498 ) 你能说中文啊？ ... @.&gt; 日期：2022 年 9 月 18 日下午 22:04 @.&gt;; @.@.&gt;; 主题： Re: [rawpython/remi] 你好，我有一个用remi做的程序，不同设备之间出现页面布局错乱的问题。我期待你的回复！（问题#498）你好，我有一个用处remi制作的程序。在我开发的电脑上，所有网页的布局都是正常运行的。程序在我的台电脑上回复的时候，页面布局是两台的屏幕了，但是是什么情况？—直接回复此邮件，在 GitHub ***@***.***&gt; 可以呀——直接回复这封邮件，在 GitHub 上查看，或者退订。您收到此消息是因为您发表了评论。消息 ID：@***。
  
有微信不 ，一起交流下

**Comment by Antonio0307** [comment]
ok



---Original---
From: "Davide ***@***.***&gt;
Date: Sun, Apr 23, 2023 20:05 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [rawpython/remi] Hello, I have a program made with remi, andthere is a problem with the page layout disorder between different devices. Ilook forward to your reply! (Issue #498)




 
Closed #498 as completed.
