### ISSUE TITLE
Can REMI be output to an image file?  (jpg, png, etc)

### ISSUE THREAD

**Issue by harwalan** [rawpython/remi#501]
I'm hoping to build an interface with REMI and then output the results into some kind of image file.  A JPG would be easily distributable.  Is this possible?

**Comment by dddomodossola** [comment]
Hello @harwalan,

Remi outputs to html. So you can save and open it everywhere with a a browser. I suppose that there should be libraries to convert from html to jpg, but never tried to do so.
Of course, saving html or images allows you to look an "offline" interface, interactivity is lost.
May I ask you why you want to convert interface to image?

Kind Regards

**Comment by harwalan** [comment]
@dddomodossola Thanks for the quick replies?

I'm playing a lot with small devices.  I have some the run CircuitPython, MicroPython or similar.  The also have a variety of displays (e-ink, LCD, etc).  One thing they will all do is display images.  A UI framework that generates an image could be useful.  It might be best to do on the devices, but even transporting to the device over HTTP is feasible.  

REMI is particularly interesting because of the ability to host a web page.

**Comment by dddomodossola** [comment]
I am actually playing with an stm32 board, just for fun. Embedded devices are really funny and useful. It would be wonderful to get remi running un such devices. However most of these little embedded devices cannot host a remi application, also because of limited resources.
