### ISSUE TITLE
Will REMI run on embedded devices with CircuitPython or MicroPython?

### ISSUE THREAD

**Issue by harwalan** [rawpython/remi#502]

**Comment by dddomodossola** [comment]
I don't know. The embedded device family is so vast that I can imagine remi could work on some devices and not on others.
MicroPython implements a small subset of python libraries, and remi uses networking features that typically are not suited for small circuits. So probably remi will not work on micropython. The same should be for CircuitPython.
Differently, remi will work without problem on SBCs like RaspberryPi. 

Have a nice day,
Davide
