### ISSUE TITLE
Video stream not seen remotely

### ISSUE THREAD

**Issue by WC802** [rawpython/remi#505]
I'm sorry to bother again. I've trying to set up a video streaming as part of an app using camera.py form the examples. This works perfectly on the browser from the computer I'm running the code but when accessing to the webpage form another computer no preview is seen. 
Thank you very much in advance.

**Comment by dddomodossola** [comment]
Hello, you can ask me all the questions you want. I'm pleased to help. Can you please show me the code of your script?

**Comment by dddomodossola** [comment]
Hello @WC802,

No problem for the code, it looks fine. Messages in spanish are also ok ;-)
The problem in your script is that you are using the wrong method to grab video. The method you used allows to get video frames by using the browser, specifically the browser of the client machine. 
You instead need to grab video from the "server", the raspberrypi, to which other machines will connect.
The correct method is to use opencv. Remi has an opencv_video widget, you can find it in the editor.
First install python opencv, than you can see the widgets in the remi gui editor.

Here is a little example for you that allows to grab video with opencv.
[opencv_video.zip](https://github.com/rawpython/remi/files/9942088/opencv_video.zip)

Please let me know if you need further information.
Have a nice day

**Comment by WC802** [comment]
I forgot to reply. It worked just fine. Thank you very much!
