### ISSUE TITLE
got an unexpected keyword argument 'websocket_port

### ISSUE THREAD

**Issue by lhlm1994** [rawpython/remi#509]
I am using Pi, and encountered a common problem about websocket_port. But when I followed the sugesstion and and websocket_port in start(). The error is got an unexpected keyword argument 'websocket_port

**Comment by dddomodossola** [comment]
Hello @lhlm1994 websocket_port is no more accepted as parameter because now remi uses only one port for all the communication. It is the parameter **port** .
