### ISSUE TITLE
Blank window on standalone_app.py

### ISSUE THREAD

**Issue by meow464** [rawpython/remi#511]
I'm on fedora 37, in a venv, python 3.11.2.
I installed pywebview[qt] and remi with pip.

python standalone_app.py results in:

```
python standalone_app.py 
remi.server      INFO     Started httpserver http://127.0.0.1:35585/
remi.request     INFO     built UI (path=/)
remi.request     DEBUG    get: /
127.0.0.1 - - [03/Mar/2023 17:08:58] "GET / HTTP/1.1" 200 -
```

Note: I added `debug=True` to the start function but it didn't give much more info.

Thnaks for Remi!

**Comment by meow464** [comment]
It was a problem with pywebview and Qt, using Gtk solved the issue.

**Comment by dddomodossola** [comment]
Thank you very much for reporting ;-)
