### ISSUE TITLE
[QUESTION] any example of long-polling implementation in remi? 

### ISSUE THREAD

**Issue by ztigerz** [rawpython/remi#513]
Hello from a newbie :).  

**[goal]** a webpage to always keep a valid HTTP GET request to webserver (long-polling).  So webserver can push data whenever ready to webpage.  

**[reference]** I found long-polling is supported by Javascript: [https://javascript.info/long-polling](url)

**[question]** Is there any example of long-polling implementation in remi? Or other similar approach recommended to meet my goal?  

thanks

**Comment by dddomodossola** [comment]
Hello @ztigerz ,

This is not required in remi. Remi automatically updates html elements that got changed on the server side. This means that, when you do something like mybutton.set_text("new text"), remi sends the message to the page immediately.

Kind Regards.
